CREATE TABLE IF NOT EXISTS AUDIOS (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      artist VARCHAR(255),
                                      release_year VARCHAR(255),
                                      album VARCHAR(255),
                                      title VARCHAR(255)
);